### ISSUE TITLE
AccessToken指定でTwitterクラスのインスタンスを生成する際にconsumerKey/consumerSecretがセットできない

### ISSUE THREAD

**Issue by shizone** [Shinsuke-Abe/twitter4s#1]
twitter4s.applyメソッドの引数としてAccessTokenを指定した場合、consumerKey/consumerSecretを設定できずIllegalStateExceptionが発生する。

``` scala
Welcome to Scala version 2.9.1.final (OpenJDK Server VM, Java 1.7.0_03).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import twitter4j.auth._
import twitter4j.auth._

scala> import twitter4s._
import twitter4s._

scala> import twitter4s.implicits._
import twitter4s.implicits._

scala> twitter4s.Twitter(accessToken = Some(new AccessToken("#####", "#####")))
java.lang.IllegalStateException: Consumer key and Consumer secret not supplied.
    at twitter4j.TwitterFactory.getInstance(TwitterFactory.java:131)
    at twitter4s.Twitter$.getTwitter4jInstance(Twitter.scala:911)
    at twitter4s.Twitter$.apply(Twitter.scala:880)
    at .<init>(<console>:17)
    at .<clinit>(<console>)
    at .<init>(<console>:11)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:704)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:914)
    at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:546)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:577)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:543)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:694)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:745)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:651)
    at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:542)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:550)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
    at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:851)
    at xsbt.ConsoleInterface.run(ConsoleInterface.scala:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:57)
    at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:48)
    at sbt.Console.console0$1(Console.scala:23)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
    at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
    at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
```

**Comment by Shinsuke-Abe** [comment]
Twitter4Jでのインスタンス生成の流れは以下でOK？

Twitter twitter = new TwitterFactory().getInstance();
twitter.setConsumer(hoge,hoge);
twitter.setOAuthAccessToken(fuga);

この流れって、Twitter4Jの制約としてConsumerは事前にセットされなくちゃ行けなくて、その制約かと。
なので、Twitter4JでもファクトリのgetInstanceメソッドにいきなりアクセストークン情報を渡すと同じ例外が出ます。
Twitter4SでもTwitter()でインスタンスを作ってTwitterクラスのメソッドを使う流れになりますが、まだセッタを一部実装していませんので、早めに実装します。
Twitterコンパニオンオブジェクトとしてどういうエンドポイントを用意してあげれば良いかアイデアがあれば教えてくれるとありがたいです。

**Comment by Shinsuke-Abe** [comment]
addapplyブランチを作成して以下のようにオブジェクトを生成できるように変更しました。
確認の上、使い勝手についての感想を教えてくれるとありがたいです。

val consumerKey = new ConsumerKey("hoge", "fuga")
val accessToken = new AccessToken("foo", "bar")

val twitterObj = Twitter(consumerKey, accessToken)

なお、consumerKey,accessTokenともに現状は必須パラメータにしてあります。

**Comment by shizone** [comment]
使い勝手についてはこの方針で問題ないと思います。
ただAccessTokenはTwitter4Jのを生で使うのではなく、ConsumerKeyと同じパッケージに新規でcase classを作ったほうがいいかなぁと思ってます。

ちょっと他の人の意見も聞きたいところではあるんですが、Twitter4Jのパッケージは意識させないほうがいいような気がします。

**Comment by Shinsuke-Abe** [comment]
確認ありがとうございます。
addapplyブランチをmasterにマージしました。

> Twitter4Jのパッケージは意識させないほうがいいような気がします。

それは、一度議論をしてみたかったところです。
基本的にはTwitter4Jで使っているオブジェクトは全てTwitter4S用にcase classでラッピングする想定です。

**Comment by Shinsuke-Abe** [comment]
AccessTokenは別イシューをあげることにして、いったんこのイシューはクローズします。
